sudo: required
language: go

go:
  - "1.x"

services:
  - docker

  env:
    global:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

before_script:
  - go get
  - go vet ./...
  - chmod +x ./scripts/dist.sh

script:
  - go build

before_deploy:
  - ./scripts/dist.sh

################# RELEASING ####################
## git tag -s -m "release information" vX.X.X ##
## git push --tags                            ##
################################################
deploy:
  provider: releases
  api_key:
    secure: XIx3ud8z/GEEEh+/ay7/ajwpdXmwTalYJR5e3wUpmZh0Uaa3S7SiYnqVxc6ukiWq7+WsQn9HuuqOhB8epSQ1cgxr2Y1r4j6BHXbOm38OJ5R6UFDzIM8iB23/p8yXoD1BIvG22NTGYVZsHE5kbnckj1pB48DAH4JxQR/41OvcriT87Gf2NR4gejluCg773byWNERvg7IjFQcGXSZgHdrbYo+qHmIU00oLSxEZBy1u3wf48fqhnrw8osT6qR4ZDGWX1bHky9UzzJiLR6I/NkA8dicOEZpPNNKBxupfbICLzoDVPnhfwwfO585Tw0ntQx4q+o9r9+27mU6860Qe59l27nIfHVYBefQ2rIvHA8wf/6i2yu8tJQay0KsjsOpwz96Yt2JrK58T4bZJXkw1ZywVgjkfO0yjGEV2+b9BaaQBiYclIn4rt8f9i/PyHqxmUoCSMMNrc0go3hvwUO6tpfSPBkdmg0LN0cJIDTshRbLMw33FEcghk0yj/Z/v6bQS3kLViKXgNDDd80E2KDI5+1uuGySSgqZj2npAvHeRHZ6dKWUu8+3unZDcfDXi8xfALMlmAKaTTwA6tdvJVBWprpOB1lLVJUGnbhJgh2GakD33MQ4FTZmNYfJ8vNRdW6SpRr3nWTAFCHh2c6NtGItkdjWi95RjgkHq9s2h63jwsdQCk8Y=
  file_glob: true
  file: dist/archives/*
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - docker buildx create --use
  - docker buildx build --platform $PLATFORMS -t stefanwichmann/kelvin .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push stefanwichmann/kelvin
